name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Run weekly to track performance over time
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Run performance tests
        run: npm run test:performance
      
      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: performance-results/
      
      - name: Check performance thresholds
        run: node tests/performance/check-thresholds.js
      
      - name: Store performance metrics
        if: github.event_name != 'pull_request'
        run: node tests/performance/store-metrics.js 